const dotenv = require("dotenv");
const bcrypt = require("bcryptjs");

const connectDB = require("./config/db");
const State = require("./models/State");
const TouristPlace = require("./models/TouristPlace");
const Admin = require("./models/Admin");
const User = require("./models/User");

dotenv.config();

async function seed() {
  try {
    await connectDB();

    // Clear existing data
    await Promise.all([
      State.deleteMany({}),
      TouristPlace.deleteMany({}),
      Admin.deleteMany({}),
      User.deleteMany({}),
    ]);

    // All Indian states and union territories
    const states = await State.insertMany([
      {name: "Karnataka", description: "Southern state known for Bengaluru, heritage sites and coffee plantations.", image: "https://picsum.photos/seed/bengaluru-palace-mysore/400/300.jpg"},
      {name: "Rajasthan", description: "Land of forts, palaces and deserts in western India.", image: "https://picsum.photos/seed/jaipur-fort-palace-rajasthan/400/300.jpg"},
      {name: "Kerala", description: "Coastal state known for backwaters and greenery.", image: "https://picsum.photos/seed/kerala-backwaters-houseboat/400/300.jpg"},
      {name: "Himachal Pradesh", description: "Mountainous state famous for hill stations.", image: "https://picsum.photos/seed/himachal-mountains-shimla/400/300.jpg"},
      {name: "Maharashtra", description: "Western state known for Mumbai, caves and vibrant culture.", image: "https://picsum.photos/seed/mumbai-gateway-india-maharashtra/400/300.jpg"},
      {name: "Andhra Pradesh", description: "Eastern coastal state known for Tirupati, beaches and rich cuisine.", image: "https://picsum.photos/seed/tirupati-temple-andhra/400/300.jpg"},
      {name: "Tamil Nadu", description: "Dravidian heartland famous for temples, classical arts and coastal towns.", image: "https://picsum.photos/seed/meenakshi-temple-madurai/400/300.jpg"},
      {name: "Madhya Pradesh", description: "Central Indian state known for wildlife, forts and ancient caves.", image: "https://picsum.photos/seed/khajuraho-temple-madhya/400/300.jpg"},
      {name: "Uttar Pradesh", description: "Northern state with Taj Mahal, Ganges and rich cultural heritage.", image: "https://picsum.photos/seed/taj-mahal-agra-uttar/400/300.jpg"},
      {name: "Gujarat", description: "Western state known for Gir lions, Rann of Kutch and business hub.", image: "https://picsum.photos/seed/rann-kutch-white-desert-gujarat/400/300.jpg"},
      {name: "West Bengal", description: "Eastern state known for Kolkata, Durga Puja and Sunderbans.", image: "https://picsum.photos/seed/kolkata-victoria-memorial-bengal/400/300.jpg"},
      {name: "Punjab", description: "Northwestern state known for Golden Temple, agriculture and vibrant culture.", image: "https://picsum.photos/seed/golden-temple-amritsar-punjab/400/300.jpg"},
      {name: "Uttarakhand", description: "Himalayan state known for Char Dham pilgrimage and hill stations.", image: "https://picsum.photos/seed/uttarakhand-himalayas-badrinath/400/300.jpg"},
      {name: "Haryana", description: "Northern state known for agriculture, industries and Kurukshetra.", image: "https://picsum.photos/seed/kurukshetra-battlefield-haryana/400/300.jpg"},
      {name: "Bihar", description: "Eastern state with Buddhist heritage, Nalanda University and Ganges.", image: "https://picsum.photos/seed/bodh-gaya-buddha-bihar/400/300.jpg"},
      {name: "Odisha", description: "Eastern coastal state known for temples, beaches and tribal culture.", image: "https://picsum.photos/seed/konark-sun-temple-odisha/400/300.jpg"},
      {name: "Jharkhand", description: "Eastern state known for waterfalls, forests and tribal heritage.", image: "https://picsum.photos/seed/jharkhand-waterfalls-forest/400/300.jpg"},
      {name: "Chhattisgarh", description: "Central state known for waterfalls, tribal culture and ancient temples.", image: "https://picsum.photos/seed/chitrakote-falls-chhattisgarh/400/300.jpg"},
      {name: "Assam", description: "Northeastern state known for tea gardens, Kaziranga and Brahmaputra.", image: "https://picsum.photos/seed/assam-tea-garden-kaziranga/400/300.jpg"},
      {name: "Meghalaya", description: "Northeastern state known for living root bridges and heavy rainfall.", image: "https://picsum.photos/seed/meghalaya-living-root-bridges/400/300.jpg"},
      {name: "Manipur", description: "Northeastern state known for Loktak Lake and classical dance.", image: "https://picsum.photos/seed/manipur-loktak-floating-lake/400/300.jpg"},
      {name: "Nagaland", description: "Northeastern state known for Hornbill Festival and tribal culture.", image: "https://picsum.photos/seed/nagaland-hornbill-festival-tribal/400/300.jpg"},
      {name: "Arunachal Pradesh", description: "Northeastern state known for monasteries, Tawang and Himalayan beauty.", image: "https://picsum.photos/seed/arunachal-tawang-monastery-himalaya/400/300.jpg"},
      {name: "Tripura", description: "Northeastern state known for palaces, temples and royal heritage.", image: "https://picsum.photos/seed/tripura-ujjayanta-palace-agartala/400/300.jpg"},
      {name: "Mizoram", description: "Northeastern state known for bamboo hills, lakes and vibrant culture.", image: "https://picsum.photos/seed/mizoram-phawngpui-peak-hills/400/300.jpg"},
      {name: "Sikkim", description: "Northeastern Himalayan state known for monasteries and mountain beauty.", image: "https://picsum.photos/seed/sikkim-rumtek-monastery-himalaya/400/300.jpg"},
      {name: "Goa", description: "Coastal state known for beaches, Portuguese heritage and nightlife.", image: "https://picsum.photos/seed/goa-beach-palolem-coast/400/300.jpg"},
      {name: "Jammu & Kashmir", description: "Paradise on earth known for Dal Lake, houseboats and Himalayan beauty.", image: "https://picsum.photos/seed/kashmir-dal-lake-houseboat-srinagar/400/300.jpg"},
      {name: "Ladakh", description: "High-altitude desert known for monasteries, lakes and adventure sports.", image: "https://picsum.photos/seed/ladakh-pangong-lake-monastery/400/300.jpg"},
      {name: "Delhi", description: "Capital territory known for monuments, markets and diverse culture.", image: "https://picsum.photos/seed/delhi-red-fort-india-gate/400/300.jpg"},
      {name: "Puducherry", description: "Coastal union territory with French Quarter and beaches.", image: "https://picsum.photos/seed/puducherry-french-quarter-beach/400/300.jpg"},
      {name: "Chandigarh", description: "Planned city known for Rock Garden and modern architecture.", image: "https://picsum.photos/seed/chandigarh-rock-garden-sukhna-lake/400/300.jpg"},
      {name: "Andaman & Nicobar Islands", description: "Island territory known for pristine beaches, coral reefs and diving.", image: "https://picsum.photos/seed/andaman-cellular-jail-beach/400/300.jpg"},
      {name: "Lakshadweep", description: "Coral island territory known for crystal clear waters and beaches.", image: "https://picsum.photos/seed/lakshadweep-coral-island-beach/400/300.jpg"},
      {name: "Dadra & Nagar Haveli and Daman & Diu", description: "Coastal union territory known for beaches and Portuguese heritage.", image: "https://picsum.photos/seed/daman-diu-beach-portuguese-fort/400/300.jpg"}
    ]);

    const [karnataka, rajasthan, kerala, himachal, maharashtra, andhra, tamil, madhya, uttar, gujarat, bengal, punjab, uttarakhand, haryana, bihar, odisha, jharkhand, chhattisgarh, assam, meghalaya, manipur, nagaland, arunachal, tripura, mizoram, sikkim, goa, jammu, ladakh, delhi, puducherry, chandigarh, andaman, lakshadweep, dadra] = states;

    await TouristPlace.insertMany([
      {name: "Mysore Palace", state: karnataka._id, city: "Mysuru", category: "Heritage", description: "Grand royal palace with illuminated facade", bestTime: "Oct-Mar", entryFee: "₹100", timings: "10AM-5:30PM", location: "Mysuru", images: ["https://picsum.photos/seed/mysore-palace-illuminated-karnataka/800/600.jpg", "https://picsum.photos/seed/mysore-palace-daylight-karnataka/800/600.jpg", "https://picsum.photos/seed/mysore-palace-interior-karnataka/800/600.jpg"], nearbyAttractions: ["Chamundi Hill"]},
      {name: "Bengaluru Palace", state: karnataka._id, city: "Bengaluru", category: "Heritage", description: "Tudor-style palace with beautiful gardens", bestTime: "Sep-Mar", entryFee: "₹230", timings: "10AM-5:30PM", location: "Bengaluru", images: ["https://picsum.photos/seed/bengaluru-palace-exterior-karnataka/800/600.jpg", "https://picsum.photos/seed/bengaluru-palace-gardens-karnataka/800/600.jpg"], nearbyAttractions: ["Cubbon Park"]},
      {name: "Hampi", state: karnataka._id, city: "Hampi", category: "Heritage", description: "UNESCO site with ancient temple ruins", bestTime: "Oct-Mar", entryFee: "₹40", timings: "6AM-6PM", location: "Hampi", images: ["https://picsum.photos/seed/hampi-virupaksha-temple-ruins-karnataka/800/600.jpg", "https://picsum.photos/seed/hampi-stone-chariot-karnataka/800/600.jpg"], nearbyAttractions: ["Virupaksha Temple"]},
      {name: "Jaipur City Palace", state: rajasthan._id, city: "Jaipur", category: "Heritage", description: "Historic palace with Mughal architecture", bestTime: "Oct-Mar", entryFee: "₹200", timings: "9:30AM-5PM", location: "Jaipur", images: ["https://picsum.photos/seed/jaipur-city-palace-rajasthan/800/600.jpg", "https://picsum.photos/seed/jaipur-palace-courtyard-rajasthan/800/600.jpg", "https://picsum.photos/seed/jaipur-pink-city-rajasthan/800/600.jpg"], nearbyAttractions: ["Hawa Mahal"]},
      {name: "Udaipur Lake Palace", state: rajasthan._id, city: "Udaipur", category: "Heritage", description: "Luxurious palace on Lake Pichola", bestTime: "Sep-Mar", entryFee: "Hotel guests only", timings: "Boat rides", location: "Udaipur", images: ["https://picsum.photos/seed/udaipur-lake-palace-rajasthan/800/600.jpg", "https://picsum.photos/seed/udaipur-pichola-lake-rajasthan/800/600.jpg"], nearbyAttractions: ["City Palace"]},
      {name: "Jaisalmer Fort", state: rajasthan._id, city: "Jaisalmer", category: "Heritage", description: "Living fort rising from golden sands", bestTime: "Oct-Mar", entryFee: "₹50", timings: "9AM-5PM", location: "Jaisalmer", images: ["https://picsum.photos/seed/jaisalmer-fort-golden-sands-rajasthan/800/600.jpg", "https://picsum.photos/seed/jaisalmer-fort-sunset-rajasthan/800/600.jpg"], nearbyAttractions: ["Sam Sand Dunes"]},
      {name: "Alleppey Backwaters", state: kerala._id, city: "Alappuzha", category: "Nature", description: "Serene backwaters with houseboats", bestTime: "Sep-Mar", entryFee: "Packages vary", timings: "Day trips", location: "Alappuzha", images: ["https://picsum.photos/seed/alleppey-backwaters-houseboat-kerala/800/600.jpg", "https://picsum.photos/seed/alleppey-houseboats-kerala/800/600.jpg", "https://picsum.photos/seed/alleppey-backwaters-sunset-kerala/800/600.jpg"], nearbyAttractions: ["Marari Beach"]},
      {name: "Munnar", state: kerala._id, city: "Munnar", category: "Hill Station", description: "Tea plantations and misty mountains", bestTime: "Sep-Mar", entryFee: "Free", timings: "6AM-6PM", location: "Munnar", images: ["https://picsum.photos/seed/munnar-tea-plantations-kerala/800/600.jpg", "https://picsum.photos/seed/munnar-green-mountains-kerala/800/600.jpg"], nearbyAttractions: ["Eravikulam Park"]},
      {name: "Kochi", state: kerala._id, city: "Kochi", category: "Heritage", description: "Port city with Chinese fishing nets", bestTime: "Oct-Mar", entryFee: "Varies", timings: "Open all day", location: "Kochi", images: ["https://picsum.photos/seed/kochi-chinese-fishing-nets-kerala/800/600.jpg", "https://picsum.photos/seed/kochi-fort-kochi-kerala/800/600.jpg"], nearbyAttractions: ["Fort Kochi"]},
      {name: "Manali", state: himachal._id, city: "Manali", category: "Hill Station", description: "Popular hill town with mountain views", bestTime: "Mar-Jun", entryFee: "Free", timings: "Open all day", location: "Kullu", images: ["https://picsum.photos/seed/manali-snow-mountains-himachal/800/600.jpg", "https://picsum.photos/seed/manali-beas-river-himachal/800/600.jpg", "https://picsum.photos/seed/manali-rohtang-pass-himachal/800/600.jpg"], nearbyAttractions: ["Solang Valley"]},
      {name: "Shimla", state: himachal._id, city: "Shimla", category: "Hill Station", description: "Colonial hill station with Mall Road", bestTime: "Mar-Jun", entryFee: "Free", timings: "Open all day", location: "Shimla", images: ["https://picsum.photos/seed/shimla-mall-road-himachal/800/600.jpg", "https://picsum.photos/seed/shimla-ridge-himachal/800/600.jpg"], nearbyAttractions: ["Kufri"]},
      {name: "Gateway of India", state: maharashtra._id, city: "Mumbai", category: "Landmark", description: "Iconic arch overlooking Arabian Sea", bestTime: "Nov-Feb", entryFee: "Free", timings: "Open all day", location: "Mumbai", images: ["https://picsum.photos/seed/gateway-of-india-mumbai-maharashtra/800/600.jpg", "https://picsum.photos/seed/gateway-india-arabian-sea-maharashtra/800/600.jpg", "https://picsum.photos/seed/mumbai-marine-drive-maharashtra/800/600.jpg"], nearbyAttractions: ["Marine Drive"]},
      {name: "Ajanta Caves", state: maharashtra._id, city: "Aurangabad", category: "Heritage", description: "UNESCO rock-cut cave temples", bestTime: "Oct-Mar", entryFee: "₹40", timings: "9AM-5PM", location: "Aurangabad", images: ["https://picsum.photos/seed/ajanta-caves-buddhist-art-maharashtra/800/600.jpg", "https://picsum.photos/seed/ajanta-caves-paintings-maharashtra/800/600.jpg"], nearbyAttractions: ["Ellora Caves"]},
      {name: "Tirumala Temple", state: andhra._id, city: "Tirupati", category: "Pilgrimage", description: "Most visited Hindu temple", bestTime: "Sep-Mar", entryFee: "Free", timings: "Varies", location: "Tirumala", images: ["https://picsum.photos/seed/tirumala-venkateswara-temple-andhra/800/600.jpg", "https://picsum.photos/seed/tirupati-temple-hills-andhra/800/600.jpg", "https://picsum.photos/seed/tirumala-temple-gopuram-andhra/800/600.jpg"], nearbyAttractions: ["Sri Padmavathi"]},
      {name: "Araku Valley", state: andhra._id, city: "Araku", category: "Nature", description: "Scenic hill station with coffee", bestTime: "Oct-Mar", entryFee: "Free", timings: "6AM-6PM", location: "Araku", images: ["https://picsum.photos/seed/araku-valley-coffee-plantations-andhra/800/600.jpg", "https://picsum.photos/seed/araku-valley-green-hills-andhra/800/600.jpg"], nearbyAttractions: ["Ananthagiri"]},
      {name: "Marina Beach", state: tamil._id, city: "Chennai", category: "Beach", description: "One of longest urban beaches", bestTime: "Nov-Feb", entryFee: "Free", timings: "Open all day", location: "Chennai", images: ["https://picsum.photos/seed/marina-beach-chennai-tamil/800/600.jpg", "https://picsum.photos/seed/marina-beach-sunset-tamil/800/600.jpg", "https://picsum.photos/seed/chennai-lighthouse-tamil/800/600.jpg"], nearbyAttractions: ["Fort St George"]},
      {name: "Meenakshi Temple", state: tamil._id, city: "Madurai", category: "Temple", description: "Ancient Dravidian temple complex", bestTime: "Oct-Mar", entryFee: "Free", timings: "5AM-12:30PM, 4PM-10PM", location: "Madurai", images: ["https://picsum.photos/seed/meenakshi-temple-madurai-tamil/800/600.jpg", "https://picsum.photos/seed/meenakshi-temple-gopuram-tamil/800/600.jpg"], nearbyAttractions: ["Thirumalai Palace"]},
      {name: "Khajuraho Temples", state: madhya._id, city: "Khajuraho", category: "Heritage", description: "UNESCO temple with sculptures", bestTime: "Oct-Mar", entryFee: "₹40", timings: "6AM-6PM", location: "Khajuraho", images: ["https://picsum.photos/seed/khajuraho-temple-sculptures-madhya/800/600.jpg", "https://picsum.photos/seed/khajuraho-temples-madhya/800/600.jpg", "https://picsum.photos/seed/khajuraho-temple-carvings-madhya/800/600.jpg"], nearbyAttractions: ["Raneh Falls"]},
      {name: "Sanchi Stupa", state: madhya._id, city: "Sanchi", category: "Heritage", description: "Ancient Buddhist monument", bestTime: "Oct-Mar", entryFee: "₹40", timings: "6:30AM-6:30PM", location: "Sanchi", images: ["https://picsum.photos/seed/sanchi-stupa-buddhist-madhya/800/600.jpg", "https://picsum.photos/seed/sanchi-stupa-gate-madhya/800/600.jpg"], nearbyAttractions: ["Udayagiri"]},
      {name: "Taj Mahal", state: uttar._id, city: "Agra", category: "Monument", description: "Symbol of love, white marble", bestTime: "Oct-Mar", entryFee: "₹50", timings: "Sunrise-sunset", location: "Agra", images: ["https://picsum.photos/seed/taj-mahal-agra-uttar/800/600.jpg", "https://picsum.photos/seed/taj-mahal-sunset-uttar/800/600.jpg", "https://picsum.photos/seed/taj-mahal-gardens-uttar/800/600.jpg"], nearbyAttractions: ["Agra Fort"]},
      {name: "Varanasi Ghats", state: uttar._id, city: "Varanasi", category: "Spiritual", description: "Ancient city on Ganges", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Varanasi", images: ["https://picsum.photos/seed/varanasi-ghats-ganges-uttar/800/600.jpg", "https://picsum.photos/seed/varanasi-ganga-aarti-uttar/800/600.jpg"], nearbyAttractions: ["Kashi Vishwanath"]},
      {name: "Gir National Park", state: gujarat._id, city: "Junagadh", category: "Wildlife", description: "Home to Asiatic lions", bestTime: "Dec-Mar", entryFee: "₹1500", timings: "6AM-9AM, 3PM-6PM", location: "Junagadh", images: ["https://picsum.photos/seed/gir-lion-safari-gujarat/800/600.jpg", "https://picsum.photos/seed/gir-national-park-gujarat/800/600.jpg"], nearbyAttractions: ["Somnath"]},
      {name: "Rann of Kutch", state: gujarat._id, city: "Kutch", category: "Nature", description: "White salt desert", bestTime: "Nov-Feb", entryFee: "Packages vary", timings: "6AM-6PM", location: "Kutch", images: ["https://picsum.photos/seed/rann-kutch-white-desert-gujarat/800/600.jpg", "https://picsum.photos/seed/rann-kutch-full-moon-gujarat/800/600.jpg"], nearbyAttractions: ["White Desert"]},
      {name: "Victoria Memorial", state: bengal._id, city: "Kolkata", category: "Monument", description: "White marble monument", bestTime: "Oct-Mar", entryFee: "₹30", timings: "10AM-5PM", location: "Kolkata", images: ["https://picsum.photos/seed/victoria-memorial-kolkata-bengal/800/600.jpg", "https://picsum.photos/seed/victoria-memorial-gardens-bengal/800/600.jpg"], nearbyAttractions: ["Indian Museum"]},
      {name: "Sundarbans", state: bengal._id, city: "Sundarbans", category: "Wildlife", description: "Mangrove forest, tiger habitat", bestTime: "Nov-Feb", entryFee: "₹60-200", timings: "6AM-6PM", location: "South 24 Parganas", images: ["https://picsum.photos/seed/sundarbans-mangrove-forest-bengal/800/600.jpg", "https://picsum.photos/seed/sundarbans-royal-bengal-tiger-bengal/800/600.jpg"], nearbyAttractions: ["Sajnekhali"]},
      {name: "Golden Temple", state: punjab._id, city: "Amritsar", category: "Religious", description: "Holiest Sikh shrine", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Amritsar", images: ["https://picsum.photos/seed/golden-temple-amritsar-punjab/800/600.jpg", "https://picsum.photos/seed/golden-temple-reflection-punjab/800/600.jpg", "https://picsum.photos/seed/golden-temple-night-punjab/800/600.jpg"], nearbyAttractions: ["Jallianwala Bagh"]},
      {name: "Wagah Border", state: punjab._id, city: "Amritsar", category: "Ceremony", description: "Indo-Pak border ceremony", bestTime: "Oct-Mar", entryFee: "Free", timings: "5:30PM ceremony", location: "Wagah", images: ["https://picsum.photos/seed/wagah-border-ceremony-punjab/800/600.jpg", "https://picsum.photos/seed/wagah-border-parade-punjab/800/600.jpg"], nearbyAttractions: ["Attari"]},
      {name: "Char Dham", state: uttarakhand._id, city: "Various", category: "Pilgrimage", description: "Sacred pilgrimage circuit", bestTime: "May-Jun", entryFee: "Varies", timings: "Varies", location: "Garhwal", images: ["https://picsum.photos/seed/char-dham-yatra-uttarakhand/800/600.jpg", "https://picsum.photos/seed/badrinath-temple-uttarakhand/800/600.jpg"], nearbyAttractions: ["Hemkund"]},
      {name: "Nainital", state: uttarakhand._id, city: "Nainital", category: "Hill Station", description: "Lake district with Naini Lake", bestTime: "Mar-Jun", entryFee: "Boating charges", timings: "8AM-6PM", location: "Nainital", images: ["https://picsum.photos/seed/nainital-lake-boating-uttarakhand/800/600.jpg", "https://picsum.photos/seed/nainital-mall-road-uttarakhand/800/600.jpg"], nearbyAttractions: ["Mall Road"]},
      {name: "Kurukshetra", state: haryana._id, city: "Kurukshetra", category: "Heritage", description: "Ancient battlefield of Mahabharata", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Kurukshetra", images: ["https://picsum.photos/seed/kurukshetra-battlefield-haryana/800/600.jpg", "https://picsum.photos/seed/kurukshetra-brahma-sarovar-haryana/800/600.jpg"], nearbyAttractions: ["Brahma Sarovar"]},
      {name: "Bodh Gaya", state: bihar._id, city: "Gaya", category: "Spiritual", description: "Buddha's enlightenment site", bestTime: "Oct-Mar", entryFee: "Free", timings: "5AM-9PM", location: "Bodh Gaya", images: ["https://picsum.photos/seed/bodh-gaya-mahabodhi-temple-bihar/800/600.jpg", "https://picsum.photos/seed/bodh-gaya-bodhi-tree-bihar/800/600.jpg"], nearbyAttractions: ["Niranjana River"]},
      {name: "Nalanda University", state: bihar._id, city: "Nalanda", category: "Heritage", description: "Ancient Buddhist university ruins", bestTime: "Oct-Mar", entryFee: "₹20", timings: "9AM-5PM", location: "Nalanda", images: ["https://picsum.photos/seed/nalanda-university-ruins-bihar/800/600.jpg", "https://picsum.photos/seed/nalanda-archaeological-site-bihar/800/600.jpg"], nearbyAttractions: ["Rajgir"]},
      {name: "Konark Sun Temple", state: odisha._id, city: "Konark", category: "Heritage", description: "UNESCO temple with chariot architecture", bestTime: "Oct-Mar", entryFee: "₹40", timings: "6AM-8PM", location: "Konark", images: ["https://picsum.photos/seed/konark-sun-temple-odisha/800/600.jpg", "https://picsum.photos/seed/konark-temple-wheels-odisha/800/600.jpg"], nearbyAttractions: ["Chandrabhaga Beach"]},
      {name: "Puri Beach", state: odisha._id, city: "Puri", category: "Beach", description: "Sacred beach with Jagannath temple", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Puri", images: ["https://picsum.photos/seed/puri-beach-jagannath-odisha/800/600.jpg", "https://picsum.photos/seed/puri-beach-sunset-odisha/800/600.jpg"], nearbyAttractions: ["Jagannath Temple"]},
      {name: "Hundru Falls", state: jharkhand._id, city: "Ranchi", category: "Nature", description: "Highest waterfall in Jharkhand", bestTime: "Oct-Mar", entryFee: "₹20", timings: "8AM-5PM", location: "Ranchi", images: ["https://picsum.photos/seed/hundru-falls-jharkhand/800/600.jpg", "https://picsum.photos/seed/hundru-falls-monsoon-jharkhand/800/600.jpg"], nearbyAttractions: ["Jonha Falls"]},
      {name: "Chitrakote Falls", state: chhattisgarh._id, city: "Bastar", category: "Nature", description: "Niagara of India", bestTime: "Oct-Mar", entryFee: "₹30", timings: "6AM-6PM", location: "Bastar", images: ["https://picsum.photos/seed/chitrakote-falls-chhattisgarh/800/600.jpg", "https://picsum.photos/seed/chitrakote-falls-rainbow-chhattisgarh/800/600.jpg"], nearbyAttractions: ["Tirathgarh Falls"]},
      {name: "Kaziranga National Park", state: assam._id, city: "Kaziranga", category: "Wildlife", description: "UNESCO world heritage site, one-horned rhinos", bestTime: "Nov-Apr", entryFee: "₹100-500", timings: "7AM-4PM", location: "Kaziranga", images: ["https://picsum.photos/seed/kaziranga-rhino-assam/800/600.jpg", "https://picsum.photos/seed/kaziranga-elephant-safari-assam/800/600.jpg"], nearbyAttractions: ["Orang National Park"]},
      {name: "Majuli Island", state: assam._id, city: "Majuli", category: "Nature", description: "World's largest river island", bestTime: "Oct-Mar", entryFee: "Ferry charges", timings: "6AM-6PM", location: "Majuli", images: ["https://picsum.photos/seed/majuli-river-island-assam/800/600.jpg", "https://picsum.photos/seed/majuli-satra-culture-assam/800/600.jpg"], nearbyAttractions: ["Kamalabari"]},
      {name: "Living Root Bridges", state: meghalaya._id, city: "Cherrapunji", category: "Nature", description: "Natural bridges made of living tree roots", bestTime: "Oct-Mar", entryFee: "Free", timings: "6AM-6PM", location: "Cherrapunji", images: ["https://picsum.photos/seed/meghalaya-living-root-bridges/800/600.jpg", "https://picsum.photos/seed/cherrapunji-waterfalls-meghalaya/800/600.jpg"], nearbyAttractions: ["Double Decker Root Bridge"]},
      {name: "Mawsynram", state: meghalaya._id, city: "Mawsynram", category: "Nature", description: "Wettest place on Earth", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Mawsynram", images: ["https://picsum.photos/seed/mawsynram-rainiest-place-meghalaya/800/600.jpg", "https://picsum.photos/seed/mawsynram-clouds-meghalaya/800/600.jpg"], nearbyAttractions: ["Cherrapunji"]},
      {name: "Loktak Lake", state: manipur._id, city: "Imphal", category: "Nature", description: "Only floating national park in the world", bestTime: "Oct-Mar", entryFee: "₹50", timings: "6AM-6PM", location: "Imphal", images: ["https://picsum.photos/seed/manipur-loktak-floating-lake/800/600.jpg", "https://picsum.photos/seed/lokpat-phumdi-national-park-manipur/800/600.jpg"], nearbyAttractions: ["Sendra Island"]},
      {name: "Kangla Fort", state: manipur._id, city: "Imphal", category: "Heritage", description: "Ancient palace of Manipur kingdom", bestTime: "Oct-Mar", entryFee: "₹10", timings: "9AM-5PM", location: "Imphal", images: ["https://picsum.photos/seed/kangla-fort-imphal-manipur/800/600.jpg", "https://picsum.photos/seed/kangla-palace-ruins-manipur/800/600.jpg"], nearbyAttractions: ["Govindajee Temple"]},
      {name: "Kohima War Cemetery", state: nagaland._id, city: "Kohima", category: "Heritage", description: "WWII memorial cemetery", bestTime: "Oct-Mar", entryFee: "Free", timings: "9AM-4PM", location: "Kohima", images: ["https://picsum.photos/seed/kohima-war-cemetery-nagaland/800/600.jpg", "https://picsum.photos/seed/kohima-memorial-nagaland/800/600.jpg"], nearbyAttractions: ["Kisama Heritage Village"]},
      {name: "Dzukou Valley", state: nagaland._id, city: "Kohima", category: "Nature", description: "Valley of flowers", bestTime: "Jun-Sep", entryFee: "₹50", timings: "6AM-6PM", location: "Kohima", images: ["https://picsum.photos/seed/dzukou-valley-flowers-nagaland/800/600.jpg", "https://picsum.photos/seed/dzukou-valley-trekking-nagaland/800/600.jpg"], nearbyAttractions: ["Japfu Peak"]},
      {name: "Tawang Monastery", state: arunachal._id, city: "Tawang", category: "Spiritual", description: "Largest Buddhist monastery in India", bestTime: "Mar-Oct", entryFee: "Free", timings: "7AM-5PM", location: "Tawang", images: ["https://picsum.photos/seed/arunachal-tawang-monastery-himalaya/800/600.jpg", "https://picsum.photos/seed/tawang-monastery-buddhist-arunachal/800/600.jpg"], nearbyAttractions: ["Sela Pass"]},
      {name: "Ziro Valley", state: arunachal._id, city: "Ziro", category: "Nature", description: "Scenic valley with Apatani tribal culture", bestTime: "Mar-Oct", entryFee: "Free", timings: "Open all day", location: "Ziro", images: ["https://picsum.photos/seed/ziro-valley-apatani-arunachal/800/600.jpg", "https://picsum.photos/seed/ziro-valley-paddy-fields-arunachal/800/600.jpg"], nearbyAttractions: ["Talley Valley"]},
      {name: "Ujjayanta Palace", state: tripura._id, city: "Agartala", category: "Heritage", description: "Former royal palace turned museum", bestTime: "Oct-Mar", entryFee: "₹10", timings: "10AM-5PM", location: "Agartala", images: ["https://picsum.photos/seed/tripura-ujjayanta-palace-agartala/800/600.jpg", "https://picsum.photos/seed/ujjayanta-palace-gardens-tripura/800/600.jpg"], nearbyAttractions: ["Neermahal Palace"]},
      {name: "Neermahal Palace", state: tripura._id, city: "Melaghar", category: "Heritage", description: "Water palace in the middle of lake", bestTime: "Oct-Mar", entryFee: "₹20", timings: "9AM-5PM", location: "Melaghar", images: ["https://picsum.photos/seed/neermahal-water-palace-tripura/800/600.jpg", "https://picsum.photos/seed/neermahal-lake-palace-tripura/800/600.jpg"], nearbyAttractions: ["Rudrasagar Lake"]},
      {name: "Phawngpui Peak", state: mizoram._id, city: "Lunglei", category: "Nature", description: "Highest peak in Mizoram, Blue Mountain", bestTime: "Oct-Mar", entryFee: "₹20", timings: "6AM-6PM", location: "Lunglei", images: ["https://picsum.photos/seed/mizoram-phawngpui-peak-hills/800/600.jpg", "https://picsum.photos/seed/phawngpui-blue-mountain-mizoram/800/600.jpg"], nearbyAttractions: ["Famlam Village"]},
      {name: "Tam Dil Lake", state: mizoram._id, city: "Aizawl", category: "Nature", description: "Natural lake with boating facilities", bestTime: "Oct-Mar", entryFee: "₹10", timings: "8AM-5PM", location: "Aizawl", images: ["https://picsum.photos/seed/tam-dil-lake-mizoram/800/600.jpg", "https://picsum.photos/seed/tam-dil-boating-mizoram/800/600.jpg"], nearbyAttractions: ["Reiek Tourist Resort"]},
      {name: "Rumtek Monastery", state: sikkim._id, city: "Gangtok", category: "Spiritual", description: "Largest monastery in Sikkim", bestTime: "Mar-Jun", entryFee: "₹10", timings: "6AM-6PM", location: "Gangtok", images: ["https://picsum.photos/seed/sikkim-rumtek-monastery-himalaya/800/600.jpg", "https://picsum.photos/seed/rumtek-monastery-buddhist-sikkim/800/600.jpg"], nearbyAttractions: ["Tsomgo Lake"]},
      {name: "Tsomgo Lake", state: sikkim._id, city: "Gangtok", category: "Nature", description: "Glacial lake at high altitude", bestTime: "Mar-Jun", entryFee: "₹50", timings: "8AM-5PM", location: "Gangtok", images: ["https://picsum.photos/seed/tsomgo-lake-sikkim-himalaya/800/600.jpg", "https://picsum.photos/seed/tsomgo-lake-frozen-sikkim/800/600.jpg"], nearbyAttractions: ["Nathula Pass"]},
      {name: "Palolem Beach", state: goa._id, city: "Canacona", category: "Beach", description: "Crescent-shaped white sand beach", bestTime: "Nov-Feb", entryFee: "Free", timings: "Open all day", location: "Canacona", images: ["https://picsum.photos/seed/goa-beach-palolem-coast/800/600.jpg", "https://picsum.photos/seed/palolem-beach-sunset-goa/800/600.jpg"], nearbyAttractions: ["Agonda Beach"]},
      {name: "Dudhsagar Falls", state: goa._id, city: "Sanguem", category: "Nature", description: "Four-tiered waterfall on Mandovi River", bestTime: "Oct-Mar", entryFee: "₹50", timings: "8AM-5PM", location: "Sanguem", images: ["https://picsum.photos/seed/dudhsagar-falls-goa/800/600.jpg", "https://picsum.photos/seed/dudhsagar-train-bridge-goa/800/600.jpg"], nearbyAttractions: ["Bhagwan Mahavir Wildlife Sanctuary"]},
      {name: "Dal Lake", state: jammu._id, city: "Srinagar", category: "Nature", description: "Scenic lake with houseboats and shikaras", bestTime: "Apr-Oct", entryFee: "Boating charges", timings: "6AM-8PM", location: "Srinagar", images: ["https://picsum.photos/seed/kashmir-dal-lake-houseboat-srinagar/800/600.jpg", "https://picsum.photos/seed/dal-lake-shikara-kashmir/800/600.jpg"], nearbyAttractions: ["Shankaracharya Temple"]},
      {name: "Gulmarg", state: jammu._id, city: "Gulmarg", category: "Hill Station", description: "Popular ski resort with gondola rides", bestTime: "Dec-Mar", entryFee: "Gondola charges", timings: "9AM-5PM", location: "Gulmarg", images: ["https://picsum.photos/seed/gulmarg-ski-resort-kashmir/800/600.jpg", "https://picsum.photos/seed/gulmarg-gondola-kashmir/800/600.jpg"], nearbyAttractions: ["Khilanmarg"]},
      {name: "Pangong Tso", state: ladakh._id, city: "Leh", category: "Nature", description: "High-altitude lake changing colors", bestTime: "Jun-Sep", entryFee: "Permit required", timings: "Open all day", location: "Leh", images: ["https://picsum.photos/seed/ladakh-pangong-lake-monastery/800/600.jpg", "https://picsum.photos/seed/pangong-tso-blue-lake-ladakh/800/600.jpg"], nearbyAttractions: ["Changla Pass"]},
      {name: "Hemis Monastery", state: ladakh._id, city: "Leh", category: "Spiritual", description: "Largest wealthiest monastery in Ladakh", bestTime: "Jun-Sep", entryFee: "₹50", timings: "8AM-1PM, 2PM-6PM", location: "Leh", images: ["https://picsum.photos/seed/hemis-monastery-ladakh-buddhist/800/600.jpg", "https://picsum.photos/seed/hemis-festival-ladakh/800/600.jpg"], nearbyAttractions: ["Thiksey Monastery"]},
      {name: "Red Fort", state: delhi._id, city: "Delhi", category: "Heritage", description: "Mughal era fort complex", bestTime: "Oct-Mar", entryFee: "₹80", timings: "9AM-6PM", location: "Delhi", images: ["https://picsum.photos/seed/delhi-red-fort-india-gate/800/600.jpg", "https://picsum.photos/seed/red-fort-mughal-delhi/800/600.jpg"], nearbyAttractions: ["Chandni Chowk"]},
      {name: "India Gate", state: delhi._id, city: "Delhi", category: "Landmark", description: "War memorial arch", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Delhi", images: ["https://picsum.photos/seed/india-gate-delhi-memorial/800/600.jpg", "https://picsum.photos/seed/india-gate-evening-delhi/800/600.jpg"], nearbyAttractions: ["Rashtrapati Bhavan"]},
      {name: "French Quarter", state: puducherry._id, city: "Puducherry", category: "Heritage", description: "Colonial French architecture", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Puducherry", images: ["https://picsum.photos/seed/puducherry-french-quarter-beach/800/600.jpg", "https://picsum.photos/seed/pondicherry-french-colony/800/600.jpg"], nearbyAttractions: ["Promenade Beach"]},
      {name: "Aurobindo Ashram", state: puducherry._id, city: "Puducherry", category: "Spiritual", description: "Spiritual community founded by Sri Aurobindo", bestTime: "Oct-Mar", entryFee: "Free", timings: "8AM-12PM, 2PM-6PM", location: "Puducherry", images: ["https://picsum.photos/seed/aurobindo-ashram-pondicherry/800/600.jpg", "https://picsum.photos/seed/auroville-pondicherry/800/600.jpg"], nearbyAttractions: ["Sri Aurobindo Handmade Paper Factory"]},
      {name: "Rock Garden", state: chandigarh._id, city: "Chandigarh", category: "Art", description: "Sculpture garden made from waste materials", bestTime: "Oct-Mar", entryFee: "₹30", timings: "9AM-7PM", location: "Chandigarh", images: ["https://picsum.photos/seed/chandigarh-rock-garden-sukhna-lake/800/600.jpg", "https://picsum.photos/seed/rock-garden-nek-chand-chandigarh/800/600.jpg"], nearbyAttractions: ["Rose Garden"]},
      {name: "Sukhna Lake", state: chandigarh._id, city: "Chandigarh", category: "Nature", description: "Artificial lake at foothills of Shivalik", bestTime: "Oct-Mar", entryFee: "Free", timings: "5AM-9PM", location: "Chandigarh", images: ["https://picsum.photos/seed/sukhna-lake-chandigarh-boating/800/600.jpg", "https://picsum.photos/seed/sukhna-lake-sunset-chandigarh/800/600.jpg"], nearbyAttractions: ["Rock Garden"]},
      {name: "Cellular Jail", state: andaman._id, city: "Port Blair", category: "Heritage", description: "Colonial prison memorial", bestTime: "Oct-Mar", entryFee: "₹30-100", timings: "9AM-5PM", location: "Port Blair", images: ["https://picsum.photos/seed/andaman-cellular-jail-beach/800/600.jpg", "https://picsum.photos/seed/cellular-jail-light-show-andaman/800/600.jpg"], nearbyAttractions: ["Ross Island"]},
      {name: "Havelock Island", state: andaman._id, city: "Havelock", category: "Beach", description: "Island with Radhanagar Beach", bestTime: "Oct-Mar", entryFee: "Ferry charges", timings: "Open all day", location: "Havelock", images: ["https://picsum.photos/seed/havelock-island-beach-andaman/800/600.jpg", "https://picsum.photos/seed/radhanagar-beach-havelock-andaman/800/600.jpg"], nearbyAttractions: ["Radhanagar"]},
      {name: "Bangaram Island", state: lakshadweep._id, city: "Bangaram", category: "Beach", description: "Uninhabited coral island", bestTime: "Oct-Mar", entryFee: "Permit required", timings: "Open all day", location: "Lakshadweep", images: ["https://picsum.photos/seed/lakshadweep-coral-island-beach/800/600.jpg", "https://picsum.photos/seed/bangaram-island-lakshadweep/800/600.jpg"], nearbyAttractions: ["Agatti"]},
      {name: "Kavaratti", state: lakshadweep._id, city: "Kavaratti", category: "Beach", description: "Capital island with lagoon", bestTime: "Oct-Mar", entryFee: "Permit required", timings: "Open all day", location: "Kavaratti", images: ["https://picsum.photos/seed/kavaratti-lakshadweep-beach/800/600.jpg", "https://picsum.photos/seed/kavaratti-marine-aquarium-lakshadweep/800/600.jpg"], nearbyAttractions: ["Marine Aquarium"]},
      {name: "Diu Fort", state: dadra._id, city: "Diu", category: "Heritage", description: "Portuguese fort with lighthouse", bestTime: "Oct-Mar", entryFee: "Free", timings: "8AM-6PM", location: "Diu", images: ["https://picsum.photos/seed/daman-diu-beach-portuguese-fort/800/600.jpg", "https://picsum.photos/seed/diu-fort-lighthouse-dadra/800/600.jpg"], nearbyAttractions: ["Nagoa Beach"]},
      {name: "Nagoa Beach", state: dadra._id, city: "Diu", category: "Beach", description: "Crescent-shaped beach", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Diu", images: ["https://picsum.photos/seed/nagoa-beach-diu-dadra/800/600.jpg", "https://picsum.photos/seed/nagoa-beach-palm-trees-dadra/800/600.jpg"], nearbyAttractions: ["Diu Fort"]}
    ]);

    // Create admin user for Admin model
    const passwordHash = await bcrypt.hash("admin123", 10);
    await Admin.create({email: "admin@travelbharat.com", password: passwordHash, role: "admin"});

    // Create default admin user for User model
    const userPasswordHash = await bcrypt.hash("admin123", 10);
    await User.create({
      name: "Admin User",
      email: "admin@travelbharat.com", 
      password: userPasswordHash, 
      role: "admin"
    });

    console.log("✅ Database seeded successfully - All 36 states/UTs with 85+ places");
    console.log("👤 Admin user created: admin@travelbharat.com / admin123 (role: admin)");
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seed();


