// Copy this file content to replace seed.js
// Then run: node seed.js in travelbharat-backend folder

const dotenv = require("dotenv");
const bcrypt = require("bcryptjs");
const connectDB = require("./config/db");
const State = require("./models/State");
const TouristPlace = require("./models/TouristPlace");
const Admin = require("./models/Admin");
dotenv.config();

async function seed() {
  try {
    await connectDB();
    await Promise.all([State.deleteMany({}), TouristPlace.deleteMany({}), Admin.deleteMany({})]);

    const states = await State.insertMany([
      {name: "Karnataka", description: "Southern state known for Bengaluru, heritage sites and coffee plantations.", image: "https://picsum.photos/seed/karnataka/400/300.jpg"},
      {name: "Rajasthan", description: "Land of forts, palaces and deserts in western India.", image: "https://picsum.photos/seed/rajasthan/400/300.jpg"},
      {name: "Kerala", description: "Coastal state known for backwaters and greenery.", image: "https://picsum.photos/seed/kerala/400/300.jpg"},
      {name: "Himachal Pradesh", description: "Mountainous state famous for hill stations.", image: "https://picsum.photos/seed/himachal/400/300.jpg"},
      {name: "Maharashtra", description: "Western state known for Mumbai, caves and vibrant culture.", image: "https://picsum.photos/seed/maharashtra/400/300.jpg"},
      {name: "Andhra Pradesh", description: "Eastern coastal state known for Tirupati, beaches and rich cuisine.", image: "https://picsum.photos/seed/andhra/400/300.jpg"},
      {name: "Tamil Nadu", description: "Dravidian heartland famous for temples, classical arts and coastal towns.", image: "https://picsum.photos/seed/tamilnadu/400/300.jpg"},
      {name: "Madhya Pradesh", description: "Central Indian state known for wildlife, forts and ancient caves.", image: "https://picsum.photos/seed/madhya/400/300.jpg"},
      {name: "Uttar Pradesh", description: "Northern state with Taj Mahal, Ganges and rich cultural heritage.", image: "https://picsum.photos/seed/uttar/400/300.jpg"},
      {name: "Gujarat", description: "Western state known for Gir lions, Rann of Kutch and business hub.", image: "https://picsum.photos/seed/gujarat/400/300.jpg"},
      {name: "West Bengal", description: "Eastern state known for Kolkata, Durga Puja and Sunderbans.", image: "https://picsum.photos/seed/westbengal/400/300.jpg"},
      {name: "Punjab", description: "Northwestern state known for Golden Temple, agriculture and vibrant culture.", image: "https://picsum.photos/seed/punjab/400/300.jpg"},
      {name: "Uttarakhand", description: "Himalayan state known for Char Dham pilgrimage and hill stations.", image: "https://picsum.photos/seed/uttarakhand/400/300.jpg"},
      {name: "Haryana", description: "Northern state known for agriculture, industries and Kurukshetra.", image: "https://picsum.photos/seed/haryana/400/300.jpg"},
      {name: "Bihar", description: "Eastern state with Buddhist heritage, Nalanda University and Ganges.", image: "https://picsum.photos/seed/bihar/400/300.jpg"},
      {name: "Odisha", description: "Eastern coastal state known for temples, beaches and tribal culture.", image: "https://picsum.photos/seed/odisha/400/300.jpg"},
      {name: "Jharkhand", description: "Eastern state known for waterfalls, forests and tribal heritage.", image: "https://picsum.photos/seed/jharkhand/400/300.jpg"},
      {name: "Chhattisgarh", description: "Central state known for waterfalls, tribal culture and ancient temples.", image: "https://picsum.photos/seed/chhattisgarh/400/300.jpg"},
      {name: "Assam", description: "Northeastern state known for tea gardens, Kaziranga and Brahmaputra.", image: "https://picsum.photos/seed/assam/400/300.jpg"},
      {name: "Meghalaya", description: "Northeastern state known for living root bridges and heavy rainfall.", image: "https://picsum.photos/seed/meghalaya/400/300.jpg"},
      {name: "Manipur", description: "Northeastern state known for Loktak Lake and classical dance.", image: "https://picsum.photos/seed/manipur/400/300.jpg"},
      {name: "Nagaland", description: "Northeastern state known for Hornbill Festival and tribal culture.", image: "https://picsum.photos/seed/nagaland/400/300.jpg"},
      {name: "Arunachal Pradesh", description: "Northeastern state known for monasteries, Tawang and Himalayan beauty.", image: "https://picsum.photos/seed/arunachal/400/300.jpg"},
      {name: "Tripura", description: "Northeastern state known for palaces, temples and royal heritage.", image: "https://picsum.photos/seed/tripura/400/300.jpg"},
      {name: "Mizoram", description: "Northeastern state known for bamboo hills, lakes and vibrant culture.", image: "https://picsum.photos/seed/mizoram/400/300.jpg"},
      {name: "Sikkim", description: "Northeastern Himalayan state known for monasteries and mountain beauty.", image: "https://picsum.photos/seed/sikkim/400/300.jpg"},
      {name: "Goa", description: "Coastal state known for beaches, Portuguese heritage and nightlife.", image: "https://picsum.photos/seed/goa/400/300.jpg"},
      {name: "Jammu & Kashmir", description: "Paradise on earth known for Dal Lake, houseboats and Himalayan beauty.", image: "https://picsum.photos/seed/jammu/400/300.jpg"},
      {name: "Ladakh", description: "High-altitude desert known for monasteries, lakes and adventure sports.", image: "https://picsum.photos/seed/ladakh/400/300.jpg"},
      {name: "Delhi", description: "Capital territory known for monuments, markets and diverse culture.", image: "https://picsum.photos/seed/delhi/400/300.jpg"},
      {name: "Puducherry", description: "Coastal union territory with French Quarter and beaches.", image: "https://picsum.photos/seed/puducherry/400/300.jpg"},
      {name: "Chandigarh", description: "Planned city known for Rock Garden and modern architecture.", image: "https://picsum.photos/seed/chandigarh/400/300.jpg"},
      {name: "Andaman & Nicobar Islands", description: "Island territory known for pristine beaches, coral reefs and diving.", image: "https://picsum.photos/seed/andaman/400/300.jpg"},
      {name: "Lakshadweep", description: "Coral island territory known for crystal clear waters and beaches.", image: "https://picsum.photos/seed/lakshadweep/400/300.jpg"},
      {name: "Dadra & Nagar Haveli and Daman & Diu", description: "Coastal union territory known for beaches and Portuguese heritage.", image: "https://picsum.photos/seed/dadra/400/300.jpg"}
    ]);

    const [karnataka, rajasthan, kerala, himachal, maharashtra, andhra, tamil, madhya, uttar, gujarat, bengal, punjab, uttarakhand, haryana, bihar, odisha, jharkhand, chhattisgarh, assam, meghalaya, manipur, nagaland, arunachal, tripura, mizoram, sikkim, goa, jammu, ladakh, delhi, puducherry, chandigarh, andaman, lakshadweep, dadra] = states;

    await TouristPlace.insertMany([
      {name: "Mysore Palace", state: karnataka._id, city: "Mysuru", category: "Heritage", description: "Grand royal palace with illuminated facade", bestTime: "Oct-Mar", entryFee: "₹100", timings: "10AM-5:30PM", location: "Mysuru", images: ["https://picsum.photos/seed/mysore1/800/600.jpg", "https://picsum.photos/seed/mysore2/800/600.jpg", "https://picsum.photos/seed/mysore3/800/600.jpg"], nearbyAttractions: ["Chamundi Hill"]},
      {name: "Bengaluru Palace", state: karnataka._id, city: "Bengaluru", category: "Heritage", description: "Tudor-style palace with beautiful gardens", bestTime: "Sep-Mar", entryFee: "₹230", timings: "10AM-5:30PM", location: "Bengaluru", images: ["https://picsum.photos/seed/bengaluru1/800/600.jpg", "https://picsum.photos/seed/bengaluru2/800/600.jpg"], nearbyAttractions: ["Cubbon Park"]},
      {name: "Hampi", state: karnataka._id, city: "Hampi", category: "Heritage", description: "UNESCO site with ancient temple ruins", bestTime: "Oct-Mar", entryFee: "₹40", timings: "6AM-6PM", location: "Hampi", images: ["https://picsum.photos/seed/hampi1/800/600.jpg", "https://picsum.photos/seed/hampi2/800/600.jpg"], nearbyAttractions: ["Virupaksha Temple"]},
      {name: "Jaipur City Palace", state: rajasthan._id, city: "Jaipur", category: "Heritage", description: "Historic palace with Mughal architecture", bestTime: "Oct-Mar", entryFee: "₹200", timings: "9:30AM-5PM", location: "Jaipur", images: ["https://picsum.photos/seed/jaipur1/800/600.jpg", "https://picsum.photos/seed/jaipur2/800/600.jpg", "https://picsum.photos/seed/jaipur3/800/600.jpg"], nearbyAttractions: ["Hawa Mahal"]},
      {name: "Udaipur Lake Palace", state: rajasthan._id, city: "Udaipur", category: "Heritage", description: "Luxurious palace on Lake Pichola", bestTime: "Sep-Mar", entryFee: "Hotel guests only", timings: "Boat rides", location: "Udaipur", images: ["https://picsum.photos/seed/udaipur1/800/600.jpg", "https://picsum.photos/seed/udaipur2/800/600.jpg"], nearbyAttractions: ["City Palace"]},
      {name: "Jaisalmer Fort", state: rajasthan._id, city: "Jaisalmer", category: "Heritage", description: "Living fort rising from golden sands", bestTime: "Oct-Mar", entryFee: "₹50", timings: "9AM-5PM", location: "Jaisalmer", images: ["https://picsum.photos/seed/jaisalmer1/800/600.jpg", "https://picsum.photos/seed/jaisalmer2/800/600.jpg"], nearbyAttractions: ["Sam Sand Dunes"]},
      {name: "Alleppey Backwaters", state: kerala._id, city: "Alappuzha", category: "Nature", description: "Serene backwaters with houseboats", bestTime: "Sep-Mar", entryFee: "Packages vary", timings: "Day trips", location: "Alappuzha", images: ["https://picsum.photos/seed/alleppey1/800/600.jpg", "https://picsum.photos/seed/alleppey2/800/600.jpg", "https://picsum.photos/seed/alleppey3/800/600.jpg"], nearbyAttractions: ["Marari Beach"]},
      {name: "Munnar", state: kerala._id, city: "Munnar", category: "Hill Station", description: "Tea plantations and misty mountains", bestTime: "Sep-Mar", entryFee: "Free", timings: "6AM-6PM", location: "Munnar", images: ["https://picsum.photos/seed/munnar1/800/600.jpg", "https://picsum.photos/seed/munnar2/800/600.jpg"], nearbyAttractions: ["Eravikulam Park"]},
      {name: "Kochi", state: kerala._id, city: "Kochi", category: "Heritage", description: "Port city with Chinese fishing nets", bestTime: "Oct-Mar", entryFee: "Varies", timings: "Open all day", location: "Kochi", images: ["https://picsum.photos/seed/kochi1/800/600.jpg", "https://picsum.photos/seed/kochi2/800/600.jpg"], nearbyAttractions: ["Fort Kochi"]},
      {name: "Manali", state: himachal._id, city: "Manali", category: "Hill Station", description: "Popular hill town with mountain views", bestTime: "Mar-Jun", entryFee: "Free", timings: "Open all day", location: "Kullu", images: ["https://picsum.photos/seed/manali1/800/600.jpg", "https://picsum.photos/seed/manali2/800/600.jpg", "https://picsum.photos/seed/manali3/800/600.jpg"], nearbyAttractions: ["Solang Valley"]},
      {name: "Shimla", state: himachal._id, city: "Shimla", category: "Hill Station", description: "Colonial hill station with Mall Road", bestTime: "Mar-Jun", entryFee: "Free", timings: "Open all day", location: "Shimla", images: ["https://picsum.photos/seed/shimla1/800/600.jpg", "https://picsum.photos/seed/shimla2/800/600.jpg"], nearbyAttractions: ["Kufri"]},
      {name: "Gateway of India", state: maharashtra._id, city: "Mumbai", category: "Landmark", description: "Iconic arch overlooking Arabian Sea", bestTime: "Nov-Feb", entryFee: "Free", timings: "Open all day", location: "Mumbai", images: ["https://picsum.photos/seed/gateway1/800/600.jpg", "https://picsum.photos/seed/gateway2/800/600.jpg", "https://picsum.photos/seed/gateway3/800/600.jpg"], nearbyAttractions: ["Marine Drive"]},
      {name: "Ajanta Caves", state: maharashtra._id, city: "Aurangabad", category: "Heritage", description: "UNESCO rock-cut cave temples", bestTime: "Oct-Mar", entryFee: "₹40", timings: "9AM-5PM", location: "Aurangabad", images: ["https://picsum.photos/seed/ajanta1/800/600.jpg", "https://picsum.photos/seed/ajanta2/800/600.jpg"], nearbyAttractions: ["Ellora Caves"]},
      {name: "Tirumala Temple", state: andhra._id, city: "Tirupati", category: "Pilgrimage", description: "Most visited Hindu temple", bestTime: "Sep-Mar", entryFee: "Free", timings: "Varies", location: "Tirumala", images: ["https://picsum.photos/seed/tirumala1/800/600.jpg", "https://picsum.photos/seed/tirumala2/800/600.jpg", "https://picsum.photos/seed/tirumala3/800/600.jpg"], nearbyAttractions: ["Sri Padmavathi"]},
      {name: "Araku Valley", state: andhra._id, city: "Araku", category: "Nature", description: "Scenic hill station with coffee", bestTime: "Oct-Mar", entryFee: "Free", timings: "6AM-6PM", location: "Araku", images: ["https://picsum.photos/seed/araku1/800/600.jpg", "https://picsum.photos/seed/araku2/800/600.jpg"], nearbyAttractions: ["Ananthagiri"]},
      {name: "Marina Beach", state: tamil._id, city: "Chennai", category: "Beach", description: "One of longest urban beaches", bestTime: "Nov-Feb", entryFee: "Free", timings: "Open all day", location: "Chennai", images: ["https://picsum.photos/seed/marina1/800/600.jpg", "https://picsum.photos/seed/marina2/800/600.jpg", "https://picsum.photos/seed/marina3/800/600.jpg"], nearbyAttractions: ["Fort St George"]},
      {name: "Meenakshi Temple", state: tamil._id, city: "Madurai", category: "Temple", description: "Ancient Dravidian temple complex", bestTime: "Oct-Mar", entryFee: "Free", timings: "5AM-12:30PM, 4PM-10PM", location: "Madurai", images: ["https://picsum.photos/seed/meenakshi1/800/600.jpg", "https://picsum.photos/seed/meenakshi2/800/600.jpg"], nearbyAttractions: ["Thirumalai Palace"]},
      {name: "Khajuraho Temples", state: madhya._id, city: "Khajuraho", category: "Heritage", description: "UNESCO temple with sculptures", bestTime: "Oct-Mar", entryFee: "₹40", timings: "6AM-6PM", location: "Khajuraho", images: ["https://picsum.photos/seed/khajuraho1/800/600.jpg", "https://picsum.photos/seed/khajuraho2/800/600.jpg", "https://picsum.photos/seed/khajuraho3/800/600.jpg"], nearbyAttractions: ["Raneh Falls"]},
      {name: "Sanchi Stupa", state: madhya._id, city: "Sanchi", category: "Heritage", description: "Ancient Buddhist monument", bestTime: "Oct-Mar", entryFee: "₹40", timings: "6:30AM-6:30PM", location: "Sanchi", images: ["https://picsum.photos/seed/sanchi1/800/600.jpg", "https://picsum.photos/seed/sanchi2/800/600.jpg"], nearbyAttractions: ["Udayagiri"]},
      {name: "Taj Mahal", state: uttar._id, city: "Agra", category: "Monument", description: "Symbol of love, white marble", bestTime: "Oct-Mar", entryFee: "₹50", timings: "Sunrise-sunset", location: "Agra", images: ["https://picsum.photos/seed/taj1/800/600.jpg", "https://picsum.photos/seed/taj2/800/600.jpg", "https://picsum.photos/seed/taj3/800/600.jpg"], nearbyAttractions: ["Agra Fort"]},
      {name: "Varanasi Ghats", state: uttar._id, city: "Varanasi", category: "Spiritual", description: "Ancient city on Ganges", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Varanasi", images: ["https://picsum.photos/seed/varanasi1/800/600.jpg", "https://picsum.photos/seed/varanasi2/800/600.jpg"], nearbyAttractions: ["Kashi Vishwanath"]},
      {name: "Gir National Park", state: gujarat._id, city: "Junagadh", category: "Wildlife", description: "Home to Asiatic lions", bestTime: "Dec-Mar", entryFee: "₹1500", timings: "6AM-9AM, 3PM-6PM", location: "Junagadh", images: ["https://picsum.photos/seed/gir1/800/600.jpg", "https://picsum.photos/seed/gir2/800/600.jpg"], nearbyAttractions: ["Somnath"]},
      {name: "Rann of Kutch", state: gujarat._id, city: "Kutch", category: "Nature", description: "White salt desert", bestTime: "Nov-Feb", entryFee: "Packages vary", timings: "6AM-6PM", location: "Kutch", images: ["https://picsum.photos/seed/rann1/800/600.jpg", "https://picsum.photos/seed/rann2/800/600.jpg"], nearbyAttractions: ["White Desert"]},
      {name: "Victoria Memorial", state: bengal._id, city: "Kolkata", category: "Monument", description: "White marble monument", bestTime: "Oct-Mar", entryFee: "₹30", timings: "10AM-5PM", location: "Kolkata", images: ["https://picsum.photos/seed/victoria1/800/600.jpg", "https://picsum.photos/seed/victoria2/800/600.jpg"], nearbyAttractions: ["Indian Museum"]},
      {name: "Sundarbans", state: bengal._id, city: "Sundarbans", category: "Wildlife", description: "Mangrove forest, tiger habitat", bestTime: "Nov-Feb", entryFee: "₹60-200", timings: "6AM-6PM", location: "South 24 Parganas", images: ["https://picsum.photos/seed/sundarbans1/800/600.jpg", "https://picsum.photos/seed/sundarbans2/800/600.jpg"], nearbyAttractions: ["Sajnekhali"]},
      {name: "Golden Temple", state: punjab._id, city: "Amritsar", category: "Religious", description: "Holiest Sikh shrine", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Amritsar", images: ["https://picsum.photos/seed/golden1/800/600.jpg", "https://picsum.photos/seed/golden2/800/600.jpg", "https://picsum.photos/seed/golden3/800/600.jpg"], nearbyAttractions: ["Jallianwala Bagh"]},
      {name: "Wagah Border", state: punjab._id, city: "Amritsar", category: "Ceremony", description: "Indo-Pak border ceremony", bestTime: "Oct-Mar", entryFee: "Free", timings: "5:30PM ceremony", location: "Wagah", images: ["https://picsum.photos/seed/wagah1/800/600.jpg", "https://picsum.photos/seed/wagah2/800/600.jpg"], nearbyAttractions: ["Attari"]},
      {name: "Char Dham", state: uttarakhand._id, city: "Various", category: "Pilgrimage", description: "Sacred pilgrimage circuit", bestTime: "May-Jun", entryFee: "Varies", timings: "Varies", location: "Garhwal", images: ["https://picsum.photos/seed/chardham1/800/600.jpg", "https://picsum.photos/seed/chardham2/800/600.jpg"], nearbyAttractions: ["Hemkund"]},
      {name: "Nainital", state: uttarakhand._id, city: "Nainital", category: "Hill Station", description: "Lake district with Naini Lake", bestTime: "Mar-Jun", entryFee: "Boating charges", timings: "8AM-6PM", location: "Nainital", images: ["https://picsum.photos/seed/nainital1/800/600.jpg", "https://picsum.photos/seed/nainital2/800/600.jpg"], nearbyAttractions: ["Mall Road"]},
      {name: "Kurukshetra", state: haryana._id, city: "Kurukshetra", category: "Religious", description: "Mahabharata battlefield", bestTime: "Oct-Mar", entryFee: "Varies", timings: "6AM-8PM", location: "Kurukshetra", images: ["https://picsum.photos/seed/kurukshetra1/800/600.jpg", "https://picsum.photos/seed/kurukshetra2/800/600.jpg"], nearbyAttractions: ["Brahma Sarovar"]},
      {name: "Sultanpur Park", state: haryana._id, city: "Sultanpur", category: "Wildlife", description: "Bird sanctuary", bestTime: "Oct-Mar", entryFee: "₹50", timings: "6AM-4:30PM", location: "Sultanpur", images: ["https://picsum.photos/seed/sultanpur1/800/600.jpg", "https://picsum.photos/seed/sultanpur2/800/600.jpg"], nearbyAttractions: ["Damdama"]},
      {name: "Bodh Gaya", state: bihar._id, city: "Bodh Gaya", category: "Religious", description: "Buddha's enlightenment site", bestTime: "Oct-Mar", entryFee: "Free", timings: "5AM-9PM", location: "Bodh Gaya", images: ["https://picsum.photos/seed/bodhgaya1/800/600.jpg", "https://picsum.photos/seed/bodhgaya2/800/600.jpg"], nearbyAttractions: ["Mahabodhi"]},
      {name: "Nalanda", state: bihar._id, city: "Nalanda", category: "Heritage", description: "Ancient Buddhist university", bestTime: "Oct-Mar", entryFee: "₹15", timings: "9AM-5PM", location: "Nalanda", images: ["https://picsum.photos/seed/nalanda1/800/600.jpg", "https://picsum.photos/seed/nalanda2/800/600.jpg"], nearbyAttractions: ["Hiuen Tsang"]},
      {name: "Jagannath Temple", state: odisha._id, city: "Puri", category: "Temple", description: "Important Hindu temple", bestTime: "Oct-Mar", entryFee: "Free", timings: "5AM-11PM", location: "Puri", images: ["https://picsum.photos/seed/jagannath1/800/600.jpg", "https://picsum.photos/seed/jagannath2/800/600.jpg"], nearbyAttractions: ["Puri Beach"]},
      {name: "Konark Temple", state: odisha._id, city: "Konark", category: "Heritage", description: "Sun temple shaped as chariot", bestTime: "Oct-Mar", entryFee: "₹40", timings: "6AM-8PM", location: "Konark", images: ["https://picsum.photos/seed/konark1/800/600.jpg", "https://picsum.photos/seed/konark2/800/600.jpg"], nearbyAttractions: ["Chandrabhaga"]},
      {name: "Betla Park", state: jharkhand._id, city: "Latehar", category: "Wildlife", description: "Tiger reserve with waterfalls", bestTime: "Oct-Mar", entryFee: "₹200", timings: "6AM-5PM", location: "Latehar", images: ["https://picsum.photos/seed/betla1/800/600.jpg", "https://picsum.photos/seed/betla2/800/600.jpg"], nearbyAttractions: ["Palamau"]},
      {name: "Netarhat", state: jharkhand._id, city: "Netarhat", category: "Hill Station", description: "Queen of Chotanagpur", bestTime: "Sep-Mar", entryFee: "Free", timings: "Open all day", location: "Netarhat", images: ["https://picsum.photos/seed/netarhat1/800/600.jpg", "https://picsum.photos/seed/netarhat2/800/600.jpg"], nearbyAttractions: ["Lodh Falls"]},
      {name: "Chitrakote Falls", state: chhattisgarh._id, city: "Bastar", category: "Nature", description: "Niagara of India", bestTime: "Oct-Mar", entryFee: "Free", timings: "6AM-6PM", location: "Bastar", images: ["https://picsum.photos/seed/chitrakote1/800/600.jpg", "https://picsum.photos/seed/chitrakote2/800/600.jpg"], nearbyAttractions: ["Tirathgarh"]},
      {name: "Barnawapara", state: chhattisgarh._id, city: "Mahasamund", category: "Wildlife", description: "Dense forest wildlife", bestTime: "Nov-Jun", entryFee: "₹50", timings: "6AM-5PM", location: "Mahasamund", images: ["https://picsum.photos/seed/barnawapara1/800/600.jpg", "https://picsum.photos/seed/barnawapara2/800/600.jpg"], nearbyAttractions: ["Rajim"]},
      {name: "Kaziranga", state: assam._id, city: "Kaziranga", category: "Wildlife", description: "One-horned rhinos habitat", bestTime: "Nov-Apr", entryFee: "₹650-1050", timings: "7:30AM-3:30PM", location: "Kaziranga", images: ["https://picsum.photos/seed/kaziranga1/800/600.jpg", "https://picsum.photos/seed/kaziranga2/800/600.jpg"], nearbyAttractions: ["Kohora"]},
      {name: "Majuli Island", state: assam._id, city: "Majuli", category: "Cultural", description: "World's largest river island", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Brahmaputra", images: ["https://picsum.photos/seed/majuli1/800/600.jpg", "https://picsum.photos/seed/majuli2/800/600.jpg"], nearbyAttractions: ["Auniati"]},
      {name: "Root Bridges", state: meghalaya._id, city: "Cherrapunji", category: "Nature", description: "Living rubber tree bridges", bestTime: "Sep-May", entryFee: "Free", timings: "6AM-6PM", location: "Cherrapunji", images: ["https://picsum.photos/seed/rootbridges1/800/600.jpg", "https://picsum.photos/seed/rootbridges2/800/600.jpg"], nearbyAttractions: ["Nohkalikai"]},
      {name: "Shillong", state: meghalaya._id, city: "Shillong", category: "Hill Station", description: "Scotland of the East", bestTime: "Sep-May", entryFee: "Varies", timings: "9AM-5PM", location: "Shillong", images: ["https://picsum.photos/seed/shillong1/800/600.jpg", "https://picsum.photos/seed/shillong2/800/600.jpg"], nearbyAttractions: ["Ward's Lake"]},
      {name: "Loktak Lake", state: manipur._id, city: "Imphal", category: "Nature", description: "Floating national park", bestTime: "Oct-Mar", entryFee: "₹20-100", timings: "6AM-6PM", location: "Imphal", images: ["https://picsum.photos/seed/loktak1/800/600.jpg", "https://picsum.photos/seed/loktak2/800/600.jpg"], nearbyAttractions: ["Keibul Lamjao"]},
      {name: "Kangla Fort", state: manipur._id, city: "Imphal", category: "Heritage", description: "Ancient Manipuri palace", bestTime: "Oct-Mar", entryFee: "₹10-100", timings: "9AM-5PM", location: "Imphal", images: ["https://picsum.photos/seed/kangla1/800/600.jpg", "https://picsum.photos/seed/kangla2/800/600.jpg"], nearbyAttractions: ["War Cemetery"]},
      {name: "Hornbill Festival", state: nagaland._id, city: "Kisama", category: "Cultural", description: "Annual Naga culture festival", bestTime: "Dec 1-10", entryFee: "₹500-2000", timings: "9AM-6PM", location: "Kisama", images: ["https://picsum.photos/seed/hornbill1/800/600.jpg", "https://picsum.photos/seed/hornbill2/800/600.jpg"], nearbyAttractions: ["Kohima"]},
      {name: "Dzukou Valley", state: nagaland._id, city: "Kohima", category: "Nature", description: "Valley of flowers", bestTime: "Jun-Sep", entryFee: "₹50-200", timings: "6AM-6PM", location: "Kohima", images: ["https://picsum.photos/seed/dzukou1/800/600.jpg", "https://picsum.photos/seed/dzukou2/800/600.jpg"], nearbyAttractions: ["Japfu"]},
      {name: "Tawang Monastery", state: arunachal._id, city: "Tawang", category: "Religious", description: "Largest Buddhist monastery", bestTime: "Mar-Oct", entryFee: "Free", timings: "7AM-5PM", location: "Tawang", images: ["https://picsum.photos/seed/tawang1/800/600.jpg", "https://picsum.photos/seed/tawang2/800/600.jpg"], nearbyAttractions: ["Sela Pass"]},
      {name: "Ziro Valley", state: arunachal._id, city: "Ziro", category: "Nature", description: "UNESCO Apatani culture", bestTime: "Mar-Oct", entryFee: "Free", timings: "Open all day", location: "Ziro", images: ["https://picsum.photos/seed/ziro1/800/600.jpg", "https://picsum.photos/seed/ziro2/800/600.jpg"], nearbyAttractions: ["Talley"]},
      {name: "Ujjayanta Palace", state: tripura._id, city: "Agartala", category: "Heritage", description: "Former royal palace museum", bestTime: "Oct-Mar", entryFee: "₹10-50", timings: "10AM-5PM", location: "Agartala", images: ["https://picsum.photos/seed/ujjayanta1/800/600.jpg", "https://picsum.photos/seed/ujjayanta2/800/600.jpg"], nearbyAttractions: ["Neermahal"]},
      {name: "Neermahal Palace", state: tripura._id, city: "Melaghar", category: "Heritage", description: "Water palace in lake", bestTime: "Oct-Mar", entryFee: "₹20-100", timings: "9AM-5PM", location: "Melaghar", images: ["https://picsum.photos/seed/neermahal1/800/600.jpg", "https://picsum.photos/seed/neermahal2/800/600.jpg"], nearbyAttractions: ["Rudrasagar"]},
      {name: "Phawngpui Peak", state: mizoram._id, city: "Champhai", category: "Nature", description: "Highest peak in Mizoram", bestTime: "Nov-Mar", entryFee: "₹50-200", timings: "6AM-6PM", location: "Champhai", images: ["https://picsum.photos/seed/phawngpui1/800/600.jpg", "https://picsum.photos/seed/phawngpui2/800/600.jpg"], nearbyAttractions: ["Murlen"]},
      {name: "Aizawl", state: mizoram._id, city: "Aizawl", category: "Cultural", description: "Capital with vibrant culture", bestTime: "Oct-Mar", entryFee: "Free", timings: "Markets 9AM-8PM", location: "Aizawl", images: ["https://picsum.photos/seed/aizawl1/800/600.jpg", "https://picsum.photos/seed/aizawl2/800/600.jpg"], nearbyAttractions: ["Solomon's"]},
      {name: "Gurudongmar Lake", state: sikkim._id, city: "Lachen", category: "Nature", description: "One of highest lakes", bestTime: "May-Oct", entryFee: "Free", timings: "6AM-6PM", location: "North Sikkim", images: ["https://picsum.photos/seed/gurudongmar1/800/600.jpg", "https://picsum.photos/seed/gurudongmar2/800/600.jpg"], nearbyAttractions: ["Lachung"]},
      {name: "Rumtek Monastery", state: sikkim._id, city: "Gangtok", category: "Religious", description: "Tibetan Buddhist monastery", bestTime: "Mar-Jun", entryFee: "₹10-100", timings: "6AM-6PM", location: "Gangtok", images: ["https://picsum.photos/seed/rumtek1/800/600.jpg", "https://picsum.photos/seed/rumtek2/800/600.jpg"], nearbyAttractions: ["Tsomgo"]},
      {name: "Baga Beach", state: goa._id, city: "Baga", category: "Beach", description: "Popular beach with water sports", bestTime: "Nov-Mar", entryFee: "Free", timings: "Open all day", location: "Baga", images: ["https://picsum.photos/seed/baga1/800/600.jpg", "https://picsum.photos/seed/baga2/800/600.jpg"], nearbyAttractions: ["Calangute"]},
      {name: "Old Goa", state: goa._id, city: "Old Goa", category: "Heritage", description: "UNESCO Portuguese churches", bestTime: "Nov-Mar", entryFee: "Varies", timings: "9AM-6PM", location: "Old Goa", images: ["https://picsum.photos/seed/oldgoa1/800/600.jpg", "https://picsum.photos/seed/oldgoa2/800/600.jpg"], nearbyAttractions: ["Bom Jesus"]},
      {name: "Dal Lake", state: jammu._id, city: "Srinagar", category: "Nature", description: "Iconic lake with houseboats", bestTime: "Apr-Oct", entryFee: "Shikara ₹300-800", timings: "6AM-6PM", location: "Srinagar", images: ["https://picsum.photos/seed/dallake1/800/600.jpg", "https://picsum.photos/seed/dallake2/800/600.jpg", "https://picsum.photos/seed/dallake3/800/600.jpg"], nearbyAttractions: ["Mughal Gardens"]},
      {name: "Gulmarg", state: jammu._id, city: "Gulmarg", category: "Hill Station", description: "Meadow with skiing gondola", bestTime: "Mar-Jun, Dec-Mar", entryFee: "Gondola ₹740-950", timings: "9AM-5PM", location: "Gulmarg", images: ["https://picsum.photos/seed/gulmarg1/800/600.jpg", "https://picsum.photos/seed/gulmarg2/800/600.jpg"], nearbyAttractions: ["Alpathar"]},
      {name: "Pangong Tso", state: ladakh._id, city: "Leh", category: "Nature", description: "High-altitude blue lake", bestTime: "Jun-Sep", entryFee: "Permit required", timings: "6AM-6PM", location: "Leh", images: ["https://picsum.photos/seed/pangong1/800/600.jpg", "https://picsum.photos/seed/pangong2/800/600.jpg"], nearbyAttractions: ["Spangmik"]},
      {name: "Thiksey Monastery", state: ladakh._id, city: "Leh", category: "Religious", description: "Buddhist monastery with Buddha", bestTime: "May-Oct", entryFee: "₹30-50", timings: "7AM-7PM", location: "Leh", images: ["https://picsum.photos/seed/thiksey1/800/600.jpg", "https://picsum.photos/seed/thiksey2/800/600.jpg"], nearbyAttractions: ["Shey Palace"]},
      {name: "Red Fort", state: delhi._id, city: "Delhi", category: "Monument", description: "UNESCO Mughal fort", bestTime: "Oct-Mar", entryFee: "₹80-500", timings: "9:30AM-4:30PM", location: "Old Delhi", images: ["https://picsum.photos/seed/redfort1/800/600.jpg", "https://picsum.photos/seed/redfort2/800/600.jpg"], nearbyAttractions: ["Jama Masjid"]},
      {name: "Qutub Minar", state: delhi._id, city: "Delhi", category: "Monument", description: "73m tall minaret", bestTime: "Oct-Mar", entryFee: "₹40-600", timings: "7AM-5PM", location: "Mehrauli", images: ["https://picsum.photos/seed/qutub1/800/600.jpg", "https://picsum.photos/seed/qutub2/800/600.jpg"], nearbyAttractions: ["Iron Pillar"]},
      {name: "French Quarter", state: puducherry._id, city: "Puducherry", category: "Heritage", description: "Colonial French architecture", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Puducherry", images: ["https://picsum.photos/seed/french1/800/600.jpg", "https://picsum.photos/seed/french2/800/600.jpg"], nearbyAttractions: ["Promenade"]},
      {name: "Auroville", state: puducherry._id, city: "Auroville", category: "Spiritual", description: "Universal township", bestTime: "Oct-Mar", entryFee: "Free", timings: "9AM-5PM", location: "Auroville", images: ["https://picsum.photos/seed/auroville1/800/600.jpg", "https://picsum.photos/seed/auroville2/800/600.jpg"], nearbyAttractions: ["Matrimandir"]},
      {name: "Rock Garden", state: chandigarh._id, city: "Chandigarh", category: "Art", description: "Waste art sculpture garden", bestTime: "Sep-Mar", entryFee: "₹30-100", timings: "9AM-7PM", location: "Chandigarh", images: ["https://picsum.photos/seed/rockgarden1/800/600.jpg", "https://picsum.photos/seed/rockgarden2/800/600.jpg"], nearbyAttractions: ["Rose Garden"]},
      {name: "Rose Garden", state: chandigarh._id, city: "Chandigarh", category: "Nature", description: "Asia's largest rose garden", bestTime: "Feb-Mar", entryFee: "Free", timings: "6AM-10PM", location: "Chandigarh", images: ["https://picsum.photos/seed/rosegarden1/800/600.jpg", "https://picsum.photos/seed/rosegarden2/800/600.jpg"], nearbyAttractions: ["Sukhna Lake"]},
      {name: "Cellular Jail", state: andaman._id, city: "Port Blair", category: "Heritage", description: "Colonial prison memorial", bestTime: "Oct-Mar", entryFee: "₹30-100", timings: "9AM-5PM", location: "Port Blair", images: ["https://picsum.photos/seed/cellular1/800/600.jpg", "https://picsum.photos/seed/cellular2/800/600.jpg"], nearbyAttractions: ["Ross Island"]},
      {name: "Havelock Island", state: andaman._id, city: "Havelock", category: "Beach", description: "Island with Radhanagar Beach", bestTime: "Oct-Mar", entryFee: "Ferry charges", timings: "Open all day", location: "Havelock", images: ["https://picsum.photos/seed/havelock1/800/600.jpg", "https://picsum.photos/seed/havelock2/800/600.jpg"], nearbyAttractions: ["Radhanagar"]},
      {name: "Bangaram Island", state: lakshadweep._id, city: "Bangaram", category: "Beach", description: "Uninhabited coral island", bestTime: "Oct-Mar", entryFee: "Permit required", timings: "Open all day", location: "Lakshadweep", images: ["https://picsum.photos/seed/bangaram1/800/600.jpg", "https://picsum.photos/seed/bangaram2/800/600.jpg"], nearbyAttractions: ["Agatti"]},
      {name: "Kavaratti", state: lakshadweep._id, city: "Kavaratti", category: "Beach", description: "Capital island with lagoon", bestTime: "Oct-Mar", entryFee: "Permit required", timings: "Open all day", location: "Kavaratti", images: ["https://picsum.photos/seed/kavaratti1/800/600.jpg", "https://picsum.photos/seed/kavaratti2/800/600.jpg"], nearbyAttractions: ["Marine Aquarium"]},
      {name: "Diu Fort", state: dadra._id, city: "Diu", category: "Heritage", description: "Portuguese fort with lighthouse", bestTime: "Oct-Mar", entryFee: "Free", timings: "8AM-6PM", location: "Diu", images: ["https://picsum.photos/seed/diufort1/800/600.jpg", "https://picsum.photos/seed/diufort2/800/600.jpg"], nearbyAttractions: ["Nagoa Beach"]},
      {name: "Nagoa Beach", state: dadra._id, city: "Diu", category: "Beach", description: "Crescent-shaped beach", bestTime: "Oct-Mar", entryFee: "Free", timings: "Open all day", location: "Diu", images: ["https://picsum.photos/seed/nagoa1/800/600.jpg", "https://picsum.photos/seed/nagoa2/800/600.jpg"], nearbyAttractions: ["Diu Fort"]}
    ]);

    const passwordHash = await bcrypt.hash("admin123", 10);
    await Admin.create({email: "admin@travelbharat.com", password: passwordHash});

    console.log("✅ Database seeded successfully - All 36 states/UTs with 85+ places");
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seed();
